// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  // Auto-generated sidebar
  mainSidebar: [
    'introduction',
    'setup',
    'run-test',
    'use-vscode',
    'build-e2e-spec',
    'refine-e2e-spec',
    'summary',

    // Auto-generated index page
    // https://docusaurus.io/docs/3.0.0-rc.0/sidebar/items#generated-index-page
    {
      type: 'category',
      label: 'Basics',
      link: {
        type: 'generated-index',
        title: 'Tutorial Basics',
        description: 'Learn about the most important Docusaurus concepts!',
        slug: '/category/basics',
        keywords: ['guides'],
        image: '/img/logo.svg',
      },
      //items: ['pages', 'docs', 'blog', 'search'],
      items: [{
        type: 'autogenerated',
        dirName: 'tutorial-basics'
      }]
    },
    /*
    {
      type: 'category',
      label: 'Extras',
      items: [{
        type: 'autogenerated',
        dirName: 'tutorial-extras'
      }]
    }
    */
  ],

  /*

  // Auto-generated sidebar
  mainSidebar: [{
    type: 'autogenerated',
    dirName: '.'
  }],

  // Manual-generated option
  mainSidebar: [
    'intro',
    'hello',
    {
      type: 'autogenerated',
      dirName: 'tutorial-basics'
    },
    {
      type: 'category',
      label: 'Extras',
      items: [{
        type: 'autogenerated',
        dirName: 'tutorial-extras'
      }]
    },
    {
      type: 'category',
      label: 'Tutorial',
      items: [
        'tutorial-basics/create-a-document'
      ],
    },
  ],

  */

};

export default sidebars;
